# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac905ef622c3a8d80897265e417eb82857ab857b43534002bcaf25285cfe882173e4c9b162f99a29058dd2b31817e934c025693139593808615a6dac925e7e6d

test:
  secret_key_base: 550d38e5294b517b4118e2bfb439fbe3caad5a3e7639b6e65803542434d5b511200c90b5e355fe10706878023fc6e2a495093b00ee5a0caf52d9433a1e8bb3b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
